---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cecnsros/public_html
    - rsync -a --delete \
        --exclude '.git' \
        --exclude '.gitignore' \
        --exclude '.cpanel.yml' \
        ./ $DEPLOYPATH/
