---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cecnsros/public_html
    - mkdir -p "$DEPLOYPATH"
    - rsync -a --delete --exclude 'cgi-bin/' --exclude 'responsables-app/' --exclude 'carpeta-didactica/' --exclude '.git/' --exclude '.cpanel.yml' --exclude '.gitignore' ./ "$DEPLOYPATH"/
