<?php
return [
    [
        'title' => 'Santa Eucaristía en el Inicio del Año Escolar 2026',
        'date_start' => '2026-02-02 07:00',
        'date_end'   => '2026-02-02 12:00',
        'category'   => 'Pastoral Educativa',
        'location'   => 'Gimnasio CECNSR',
        'summary'    => 'Exposiciones y proyectos STEAM por niveles.',
        'cover'      => 'assets/img/eventos/02-02-2026/img4-lado-izquierdo-cancha.jpg',
        'gallery'    => [
            'assets/img/eventos/02-02-2026/img0-san-francisco-escenario-cancha.jpg',
            'assets/img/eventos/02-02-2026/img1-entrada-puerta-santa.jpg',
            'assets/img/eventos/02-02-2026/img2-entrada-puerta-santa.jpg',
            'assets/img/eventos/02-02-2026/img3-desde-escenario.jpg',
            'assets/img/eventos/02-02-2026/img4-lado-izquierdo-cancha.jpg',
            'assets/img/eventos/02-02-2026/img5-consagracion.jpg',
        ],
        'href'       => 'mapa-del-sitio.php#eventos', // o una página /eventos.php si luego la creas
    ],
    [
        'title' => 'Miércoles de Ceniza',
        'date_start' => '2026-02-18 07:00',
        'date_end'   => '2026-02-18 10:00',
        'category'   => 'Pastoral Educativa',
        'location'   => 'Gimnasio CECNSR',
        'summary'    => 'Santa Eucaristía',
        'cover'      => 'assets/img/eventos/mie-ceniza/img2.jpg',
        'gallery'    => [
            'assets/img/eventos/mie-ceniza/img1.jpg',
            'assets/img/eventos/mie-ceniza/img2.jpg',
            'assets/img/eventos/mie-ceniza/img3.jpg',
            'assets/img/eventos/mie-ceniza/img4.jpg',
            'assets/img/eventos/mie-ceniza/img5.jpg',
            'assets/img/eventos/mie-ceniza/img6.jpg',
            'assets/img/eventos/mie-ceniza/img7.jpg',
            'assets/img/eventos/mie-ceniza/img8.jpg',
        ],
        'href'       => 'pastoral-educativa.php',
    ],
    [
        'title' => 'Primer Via Crucis',
        'date_start' => '2026-02-20 07:00',
        'date_end'   => '2026-02-20 9:00',
        'category'   => 'Pastoral Educativa',
        'location'   => 'Senderos del CECNSR',
        'summary'    => 'Reflexión con estudiantes.',
        'cover'      => 'assets/img/eventos/via-crucis1/img1.jpg',
        'gallery'    => [
            'assets/img/eventos/via-crucis1/img1.jpg',
            'assets/img/eventos/via-crucis1/img2.jpg',
            'assets/img/eventos/via-crucis1/img3.jpg',
            'assets/img/eventos/via-crucis1/img4.jpg',
            'assets/img/eventos/via-crucis1/img5.jpg',
            'assets/img/eventos/via-crucis1/img6.jpg',
        ],
        'href'       => 'pastoral-educativa.php',
    ],
];
